/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.real;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        final BankStatementParser bankStatementCSVParser = new BankStatementCSVParser();

        BankAnalyzer.analyze(bankStatementCSVParser);
    }

}
