/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.real;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class App {

    public String getGreeting() {
        return "The total for all transactions is ";
    }

    private static final String RESOURCE = "/Users/jihwooon/Workspaces/real-world-software-development/chapter1/src/main/resources/file.csv";

    public static void main(String[] args) throws IOException {
        final Path path = Paths.get(RESOURCE);
        final List<String> lines = Files.readAllLines(path);

        final DateTimeFormatter DATE_PATTERN = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        double total = 0d;

        for (final String line : lines) {
            final String[] columns = line.split(",");
            final LocalDate date = LocalDate.parse(columns[0], DATE_PATTERN);

            if (date.getMonth() == Month.JANUARY) {
                final double amount = Double.parseDouble(columns[1]);
                total += amount;
            }
        }

        System.out.println(new App().getGreeting() + total);
    }
}
